config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  root "lists#index"

  # # see all the lists
  # get "lists", to: "lists#index"

  # # create new list

  # # see one item on list
  # get "lists/:id", to: "lists#show", as: :list
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :lists

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @movies = Movie.all
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid h-30">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwc7ydFE1mQgADVYt1kGx89OfZYArFccguWg&usqp=CAU" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My List", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", "#", class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://pyxis.nymag.com/v1/imgs/978/4d0/4b4779e1dcb86984abe55c08366f9babe7-13-empty-theater.rhorizontal.w700.jpg);">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>Classic</p>
  </div>
</div>


<div class="container mt-5 bd-highlight mb-3">
  <div class="d-flex justify-content-between">
    <h2>My List</h2>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-primary mb-3"%>
  </div>

  <div class="cards d-flex flex-wrap">
    <% @lists.each do |list|%>
      <div class="card-category" style="width: 18rem;" >
        <%# <img src="..." class="card-img-top" alt="..."> %>
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>


</div>

app/views/lists/new.html.erb
<!-- app/views/restaurants/edit.html.erb -->

<%= form_with model: @list do |f| %>
  <div class="mb-3">
    <%= f.label :name,  class: "form-label" %>
    <%= f.text_field :name, class: "form-control w-50"%>
  </div>
  <div class="mb-3">
    <%= f.submit "Save",  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid h-30">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwc7ydFE1mQgADVYt1kGx89OfZYArFccguWg&usqp=CAU" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My List", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", "#", class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://pyxis.nymag.com/v1/imgs/978/4d0/4b4779e1dcb86984abe55c08366f9babe7-13-empty-theater.rhorizontal.w700.jpg);">
  <div class="container">
    <h1>Classic movies</h1>
  </div>
</div>

<div class="container mt-5 d-flex flex-row bd-highlight mb-3  mx-auto my-auto">
  <% @movies.each do |movie|%>
     <% movie_bookmarks = movie.bookmarks.where(list_id: @list) %>
     <% movie_bookmarks.each do |bookmark| %>
    <div class="card m-1" style="width: 18rem;">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= movie.title %></h5>
        <p class="card-text"><%= movie.overview %></p>
          <%= link_to "Delete", bookmark_path(bookmark),
                      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                      class: "btn btn-danger" %>

        <%# <p class="card-text">Some quic and make up the bulk of the card's content.</p> %>
        <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
      </div>
    </div>
    <% end %>
  <% end %>
</div>